/**
 * Copyright (C) 2024 AIDC-AI
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.langengine.agentframework.model.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * This class was generated by Ali-Generator
 * @author xiaoxuan.lp
 */
public class AgentProcessDefineParam {
    /**
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     *
     * @mbg.generated
     */
    @Deprecated
    protected boolean distinct;

    /**
     *
     * @mbg.generated
     */
    protected boolean page;

    /**
     *
     * @mbg.generated
     */
    protected int pageIndex;

    /**
     *
     * @mbg.generated
     */
    protected int pageSize;

    /**
     *
     * @mbg.generated
     */
    protected int pageStart;

    /**
     *
     * @mbg.generated
     */
    protected String distinctSql;

    /**
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     * @mbg.generated
     */
    public AgentProcessDefineParam() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * @param orderCondition
     * @param sortType
     * @return
     *
     * @mbg.generated
     */
    public AgentProcessDefineParam appendOrderByClause(OrderCondition orderCondition, SortType sortType) {
        if (null != orderByClause) {
            orderByClause = orderByClause + ", " + orderCondition.getColumnName() + " " + sortType.getValue();
        } else {
            orderByClause = orderCondition.getColumnName() + " " + sortType.getValue();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * @param distinct
     *
     * @mbg.generated
     */
    @Deprecated
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    @Deprecated
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * @param page
     * @return
     *
     * @mbg.generated
     */
    public AgentProcessDefineParam setPage(boolean page) {
        this.page = page;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public boolean isPage() {
        return page;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageIndex() {
        return pageIndex;
    }

    /**
     * @param pageSize
     * @return
     *
     * @mbg.generated
     */
    public AgentProcessDefineParam setPageSize(int pageSize) {
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * @param pageStart
     * @return
     *
     * @mbg.generated
     */
    public AgentProcessDefineParam setPageStart(int pageStart) {
        this.pageStart = pageStart < 1 ? 1 : pageStart;
        this.pageIndex = (this.pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageStart() {
        return pageStart;
    }

    /**
     * @param pageStart
     * @param pageSize
     *
     * @mbg.generated
     */
    public void setPagination(int pageStart, int pageSize) {
        this.page = true;
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
    }

    /**
     * @param condition
     * @return
     *
     * @mbg.generated
     */
    public AgentProcessDefineParam appendDistinct(OrderCondition condition) {
        if (null != distinctSql){
            distinctSql = distinctSql + ", " + condition.getColumnName();
        } else {
            distinctSql = condition.getColumnName();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * @param criteria
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *
     * @mbg.generated
     */
    protected abstract static class AbstractGeneratedCriteria {
        protected List<Criterion> criteria;

        protected AbstractGeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdIsNull() {
            addCriterion("process_definition_id is null");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdIsNotNull() {
            addCriterion("process_definition_id is not null");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdEqualTo(String value) {
            addCriterion("process_definition_id =", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotEqualTo(String value) {
            addCriterion("process_definition_id <>", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdGreaterThan(String value) {
            addCriterion("process_definition_id >", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdGreaterThanOrEqualTo(String value) {
            addCriterion("process_definition_id >=", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdLessThan(String value) {
            addCriterion("process_definition_id <", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdLessThanOrEqualTo(String value) {
            addCriterion("process_definition_id <=", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdLike(String value) {
            addCriterion("process_definition_id like", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotLike(String value) {
            addCriterion("process_definition_id not like", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdIn(List<String> values) {
            addCriterion("process_definition_id in", values, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotIn(List<String> values) {
            addCriterion("process_definition_id not in", values, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdBetween(String value1, String value2) {
            addCriterion("process_definition_id between", value1, value2, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotBetween(String value1, String value2) {
            addCriterion("process_definition_id not between", value1, value2, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionIsNull() {
            addCriterion("process_definition_version is null");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionIsNotNull() {
            addCriterion("process_definition_version is not null");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionEqualTo(Integer value) {
            addCriterion("process_definition_version =", value, "processDefinitionVersion");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionNotEqualTo(Integer value) {
            addCriterion("process_definition_version <>", value, "processDefinitionVersion");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionGreaterThan(Integer value) {
            addCriterion("process_definition_version >", value, "processDefinitionVersion");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("process_definition_version >=", value, "processDefinitionVersion");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionLessThan(Integer value) {
            addCriterion("process_definition_version <", value, "processDefinitionVersion");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionLessThanOrEqualTo(Integer value) {
            addCriterion("process_definition_version <=", value, "processDefinitionVersion");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionIn(List<Integer> values) {
            addCriterion("process_definition_version in", values, "processDefinitionVersion");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionNotIn(List<Integer> values) {
            addCriterion("process_definition_version not in", values, "processDefinitionVersion");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionBetween(Integer value1, Integer value2) {
            addCriterion("process_definition_version between", value1, value2, "processDefinitionVersion");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("process_definition_version not between", value1, value2, "processDefinitionVersion");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeIsNull() {
            addCriterion("process_definition_type is null");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeIsNotNull() {
            addCriterion("process_definition_type is not null");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeEqualTo(Integer value) {
            addCriterion("process_definition_type =", value, "processDefinitionType");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeNotEqualTo(Integer value) {
            addCriterion("process_definition_type <>", value, "processDefinitionType");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeGreaterThan(Integer value) {
            addCriterion("process_definition_type >", value, "processDefinitionType");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("process_definition_type >=", value, "processDefinitionType");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeLessThan(Integer value) {
            addCriterion("process_definition_type <", value, "processDefinitionType");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeLessThanOrEqualTo(Integer value) {
            addCriterion("process_definition_type <=", value, "processDefinitionType");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeIn(List<Integer> values) {
            addCriterion("process_definition_type in", values, "processDefinitionType");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeNotIn(List<Integer> values) {
            addCriterion("process_definition_type not in", values, "processDefinitionType");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeBetween(Integer value1, Integer value2) {
            addCriterion("process_definition_type between", value1, value2, "processDefinitionType");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("process_definition_type not between", value1, value2, "processDefinitionType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameIsNull() {
            addCriterion("process_definition_name is null");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameIsNotNull() {
            addCriterion("process_definition_name is not null");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameEqualTo(String value) {
            addCriterion("process_definition_name =", value, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameNotEqualTo(String value) {
            addCriterion("process_definition_name <>", value, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameGreaterThan(String value) {
            addCriterion("process_definition_name >", value, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameGreaterThanOrEqualTo(String value) {
            addCriterion("process_definition_name >=", value, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameLessThan(String value) {
            addCriterion("process_definition_name <", value, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameLessThanOrEqualTo(String value) {
            addCriterion("process_definition_name <=", value, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameLike(String value) {
            addCriterion("process_definition_name like", value, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameNotLike(String value) {
            addCriterion("process_definition_name not like", value, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameIn(List<String> values) {
            addCriterion("process_definition_name in", values, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameNotIn(List<String> values) {
            addCriterion("process_definition_name not in", values, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameBetween(String value1, String value2) {
            addCriterion("process_definition_name between", value1, value2, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameNotBetween(String value1, String value2) {
            addCriterion("process_definition_name not between", value1, value2, "processDefinitionName");
            return (Criteria) this;
        }

        public Criteria andIdEqualToWhenPresent(Long value) {
            if(value != null) {
                addCriterion("id =", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdNotEqualToWhenPresent(Long value) {
            if(value != null) {
                addCriterion("id <>", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanWhenPresent(Long value) {
            if(value != null) {
                addCriterion("id >", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualToWhenPresent(Long value) {
            if(value != null) {
                addCriterion("id >=", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdLessThanWhenPresent(Long value) {
            if(value != null) {
                addCriterion("id <", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualToWhenPresent(Long value) {
            if(value != null) {
                addCriterion("id <=", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdInWhenPresent(List<Long> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("id in", values, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdNotInWhenPresent(List<Long> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("id not in", values, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdBetweenWhenPresent(Long value1, Long value2) {
            if(value1 != null && value2 != null){
                addCriterion("id between", value1, value2, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdNotBetweenWhenPresent(Long value1, Long value2) {
            if(value1 != null && value2 != null){
                addCriterion("id not between", value1, value2, "id");
            }
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualToWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_create =", value, "gmtCreate");
            }
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualToWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_create <>", value, "gmtCreate");
            }
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_create >", value, "gmtCreate");
            }
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualToWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_create >=", value, "gmtCreate");
            }
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_create <", value, "gmtCreate");
            }
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualToWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_create <=", value, "gmtCreate");
            }
            return (Criteria) this;
        }

        public Criteria andGmtCreateInWhenPresent(List<Date> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("gmt_create in", values, "gmtCreate");
            }
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotInWhenPresent(List<Date> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("gmt_create not in", values, "gmtCreate");
            }
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetweenWhenPresent(Date value1, Date value2) {
            if(value1 != null && value2 != null){
                addCriterion("gmt_create between", value1, value2, "gmtCreate");
            }
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetweenWhenPresent(Date value1, Date value2) {
            if(value1 != null && value2 != null){
                addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            }
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualToWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_modified =", value, "gmtModified");
            }
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualToWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_modified <>", value, "gmtModified");
            }
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_modified >", value, "gmtModified");
            }
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualToWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_modified >=", value, "gmtModified");
            }
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_modified <", value, "gmtModified");
            }
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualToWhenPresent(Date value) {
            if(value != null) {
                addCriterion("gmt_modified <=", value, "gmtModified");
            }
            return (Criteria) this;
        }

        public Criteria andGmtModifiedInWhenPresent(List<Date> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("gmt_modified in", values, "gmtModified");
            }
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotInWhenPresent(List<Date> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("gmt_modified not in", values, "gmtModified");
            }
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetweenWhenPresent(Date value1, Date value2) {
            if(value1 != null && value2 != null){
                addCriterion("gmt_modified between", value1, value2, "gmtModified");
            }
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetweenWhenPresent(Date value1, Date value2) {
            if(value1 != null && value2 != null){
                addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdEqualToWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_id =", value, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotEqualToWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_id <>", value, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdGreaterThanWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_id >", value, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdGreaterThanOrEqualToWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_id >=", value, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdLessThanWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_id <", value, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdLessThanOrEqualToWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_id <=", value, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdLikeWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_id like", value, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotLikeWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_id not like", value, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdInWhenPresent(List<String> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("process_definition_id in", values, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotInWhenPresent(List<String> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("process_definition_id not in", values, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdBetweenWhenPresent(String value1, String value2) {
            if(value1 != null && value2 != null){
                addCriterion("process_definition_id between", value1, value2, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotBetweenWhenPresent(String value1, String value2) {
            if(value1 != null && value2 != null){
                addCriterion("process_definition_id not between", value1, value2, "processDefinitionId");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_version =", value, "processDefinitionVersion");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionNotEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_version <>", value, "processDefinitionVersion");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionGreaterThanWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_version >", value, "processDefinitionVersion");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionGreaterThanOrEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_version >=", value, "processDefinitionVersion");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionLessThanWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_version <", value, "processDefinitionVersion");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionLessThanOrEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_version <=", value, "processDefinitionVersion");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionInWhenPresent(List<Integer> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("process_definition_version in", values, "processDefinitionVersion");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionNotInWhenPresent(List<Integer> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("process_definition_version not in", values, "processDefinitionVersion");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionBetweenWhenPresent(Integer value1, Integer value2) {
            if(value1 != null && value2 != null){
                addCriterion("process_definition_version between", value1, value2, "processDefinitionVersion");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionVersionNotBetweenWhenPresent(Integer value1, Integer value2) {
            if(value1 != null && value2 != null){
                addCriterion("process_definition_version not between", value1, value2, "processDefinitionVersion");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_type =", value, "processDefinitionType");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeNotEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_type <>", value, "processDefinitionType");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeGreaterThanWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_type >", value, "processDefinitionType");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeGreaterThanOrEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_type >=", value, "processDefinitionType");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeLessThanWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_type <", value, "processDefinitionType");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeLessThanOrEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("process_definition_type <=", value, "processDefinitionType");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeInWhenPresent(List<Integer> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("process_definition_type in", values, "processDefinitionType");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeNotInWhenPresent(List<Integer> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("process_definition_type not in", values, "processDefinitionType");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeBetweenWhenPresent(Integer value1, Integer value2) {
            if(value1 != null && value2 != null){
                addCriterion("process_definition_type between", value1, value2, "processDefinitionType");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionTypeNotBetweenWhenPresent(Integer value1, Integer value2) {
            if(value1 != null && value2 != null){
                addCriterion("process_definition_type not between", value1, value2, "processDefinitionType");
            }
            return (Criteria) this;
        }

        public Criteria andStatusEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("status =", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("status <>", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("status >", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("status >=", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusLessThanWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("status <", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualToWhenPresent(Integer value) {
            if(value != null) {
                addCriterion("status <=", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusInWhenPresent(List<Integer> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("status in", values, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusNotInWhenPresent(List<Integer> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("status not in", values, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusBetweenWhenPresent(Integer value1, Integer value2) {
            if(value1 != null && value2 != null){
                addCriterion("status between", value1, value2, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusNotBetweenWhenPresent(Integer value1, Integer value2) {
            if(value1 != null && value2 != null){
                addCriterion("status not between", value1, value2, "status");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameEqualToWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_name =", value, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameNotEqualToWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_name <>", value, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameGreaterThanWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_name >", value, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameGreaterThanOrEqualToWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_name >=", value, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameLessThanWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_name <", value, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameLessThanOrEqualToWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_name <=", value, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameLikeWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_name like", value, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameNotLikeWhenPresent(String value) {
            if(value != null) {
                addCriterion("process_definition_name not like", value, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameInWhenPresent(List<String> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("process_definition_name in", values, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameNotInWhenPresent(List<String> values) {
            if(values != null && !values.isEmpty()){
                addCriterion("process_definition_name not in", values, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameBetweenWhenPresent(String value1, String value2) {
            if(value1 != null && value2 != null){
                addCriterion("process_definition_name between", value1, value2, "processDefinitionName");
            }
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionNameNotBetweenWhenPresent(String value1, String value2) {
            if(value1 != null && value2 != null){
                addCriterion("process_definition_name not between", value1, value2, "processDefinitionName");
            }
            return (Criteria) this;
        }
    }

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends AbstractGeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum OrderCondition {
        /**
         *PK
         */
        ID("id"),
        /**
         *create time
         */
        GMTCREATE("gmt_create"),
        /**
         *modification time
         */
        GMTMODIFIED("gmt_modified"),
        /**
         *流程定义id
         */
        PROCESSDEFINITIONID("process_definition_id"),
        /**
         *流程定义id 版本号
         */
        PROCESSDEFINITIONVERSION("process_definition_version"),
        /**
         *流程定义类型
         */
        PROCESSDEFINITIONTYPE("process_definition_type"),
        /**
         *状态 1:上线中 2:已下线
         */
        STATUS("status"),
        /**
         *流程定义名称
         */
        PROCESSDEFINITIONNAME("process_definition_name");

        private String columnName;

        OrderCondition(String columnName) {
            this.columnName = columnName;
        }

        public String getColumnName() {
            return columnName;
        }

        public static OrderCondition getEnumByName(String name) {
            OrderCondition[] orderConditions = OrderCondition.values();
            for (OrderCondition orderCondition : orderConditions) {
                if (orderCondition.name().equalsIgnoreCase(name)) {
                    return orderCondition;
                }
            }
            throw new RuntimeException("OrderCondition of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return columnName;
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum SortType {
        /**
         * 升序
         */
        ASC("asc"),
        /**
         * 降序
         */
        DESC("desc");

        private String value;

        SortType(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        public static SortType getEnumByName(String name) {
            SortType[] sortTypes = SortType.values();
            for (SortType sortType : sortTypes) {
                if (sortType.name().equalsIgnoreCase(name)) {
                    return sortType;
                }
            }
            throw new RuntimeException("SortType of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return value;
        }
    }
}